version: '2'
services:
    reporting_fullstack-app:
        image: reporting_fullstack
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reporting_fullstack-mysql:3306/reporting_fullstack?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 3789:8080
    reporting_fullstack-mysql:
        extends:
            file: mysql.yml
            service: reporting_fullstack-mysql
